Add filter for initial data sync
bcc-code/bcc-vote pull request #348
Opened 2022-02-09 15:25 UTC by JakubC-projects

Containes a few changes:
1. Adds lastChanged to poll-result collection
2. Refactors poll-result class
3. Adds a query when registering firestore listeners, so we don't get the whole collection on the initial load.

I suspect that the initial loading of whole collection was the cause of the bug described in #1738 though I wasn't able to confirm that. That change will be beneficial eitherway as it's going to reduce startup time and firestore costs (by about 200kr per month)

2022-02-09 16:11 UTC, elpenny requested changes
1. build is failing for now.
2. please add some test to cover changed functionality.

2022-02-10 09:20 UTC, elpenny approved these changes

2022-02-10 09:20 UTC, elpenny commented on server/src/channels.ts
> +        if(!data.firestore)return;
space before return

2022-02-10 09:20 UTC, elpenny commented on server/src/channels.ts
> +        if(data.firestore) return;
wrong conditional

2022-02-10 09:20 UTC, elpenny commented on server/src/domain/PollResult.ts
> +}
missing EOF line

2022-02-10 09:20 UTC, elpenny commented on server/src/domain/index.ts
> +export * from './PollResult';
missing EOF line

2022-02-10 09:22 UTC, JakubC-projects commented on server/src/channels.ts
> +        if(data.firestore) return;
fixed

2022-02-10 09:22 UTC, JakubC-projects commented on server/src/domain/PollResult.ts
> +}
fixed

2022-02-10 09:22 UTC, JakubC-projects commented on server/src/domain/index.ts
> +export * from './PollResult';
fixed

2022-02-10 09:23 UTC, merged